# Generated by Django 4.2.30 on 2026-09-24 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locaux', '0003_alter_local_options_local_continent_local_pays_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('loyer', models.DecimalField(decimal_places=0, help_text='Loyer mensuel en BIF', max_digits=12)),
                ('contact_telephone', models.CharField(max_length=30)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=30)),
                ('statut', models.CharField(choices=[('publiee', 'Publiée'), ('louee', 'Louée'), ('retiree', 'Retirée')], default='publiee', max_length=20)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retrait', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='locaux.local')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_publiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='AnnoncePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.BinaryField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce')),
            ],
            options={
                'verbose_name': "Photo d'annonce",
                'verbose_name_plural': "Photos d'annonces",
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
