# Generated by Django 6.0.5 on 2026-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse_province', models.CharField(blank=True, max_length=100)),
                ('adresse_commune', models.CharField(blank=True, max_length=100)),
                ('adresse_quartier', models.CharField(blank=True, max_length=100)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
