# Generated by Django 4.2.30 on 2026-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse_province', models.CharField(blank=True, max_length=100)),
                ('adresse_commune', models.CharField(blank=True, max_length=100)),
                ('adresse_quartier', models.CharField(blank=True, max_length=100)),
                ('mot_de_passe_temp', models.CharField(blank=True, default='', max_length=128)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='proprietaire',
            constraint=models.UniqueConstraint(fields=('email',), name='uniq_proprietaire_email'),
        ),
        migrations.AddConstraint(
            model_name='proprietaire',
            constraint=models.UniqueConstraint(fields=('telephone',), name='uniq_proprietaire_telephone'),
        ),
    ]
