# Generated by Django 4.2.30 on 2026-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='mot_de_passe_temp',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
