# Generated by Django 4.2.30 on 2026-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaires', '0002_remove_proprietaire_mot_de_passe_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='cni',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='nif',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='proprietaire',
            constraint=models.UniqueConstraint(fields=('nif',), name='uniq_proprietaire_nif'),
        ),
    ]
