# Generated by Django 4.2.30 on 2026-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaires', '0002_proprietaire_mot_de_passe_temp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proprietaire',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='uniq_proprietaire_email'),
        ),
        migrations.AddConstraint(
            model_name='proprietaire',
            constraint=models.UniqueConstraint(condition=models.Q(('telephone', ''), _negated=True), fields=('telephone',), name='uniq_proprietaire_telephone'),
        ),
    ]
