# Generated by Django 4.2.30 on 2026-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse_postale', models.CharField(blank=True, max_length=300)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('mot_de_passe_temp', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom_prenom'],
            },
        ),
        migrations.AddConstraint(
            model_name='locataire',
            constraint=models.UniqueConstraint(fields=('email',), name='uniq_locataire_email'),
        ),
        migrations.AddConstraint(
            model_name='locataire',
            constraint=models.UniqueConstraint(fields=('telephone',), name='uniq_locataire_telephone'),
        ),
    ]
