# Generated by Django 4.2.30 on 2026-08-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataire',
            name='mot_de_passe_temp',
        ),
        migrations.AddField(
            model_name='locataire',
            name='activation_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='locataire',
            name='expiration_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
