# Generated by Django 4.2.30 on 2026-06-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locataires', '0002_locataire_mot_de_passe_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataire_profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
