# Generated by Django 4.2.30 on 2026-06-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0003_locataire_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataire',
            name='user',
        ),
    ]
