# Generated by Django 4.2.30 on 2026-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0004_remove_locataire_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locataire',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='uniq_locataire_email'),
        ),
        migrations.AddConstraint(
            model_name='locataire',
            constraint=models.UniqueConstraint(condition=models.Q(('telephone', ''), _negated=True), fields=('telephone',), name='uniq_locataire_telephone'),
        ),
    ]
