# Generated by Django 4.2.30 on 2026-07-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immeubles', '0001_initial'),
        ('locaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_charge', models.CharField(choices=[('travaux', 'Travaux/Entretien'), ('impot_locatif', 'Impôt locatif'), ('impot_foncier', 'Taxe foncière'), ('frais_cabinet', 'Frais cabinet'), ('arrieres', 'Arriérés'), ('assurance', 'Assurance'), ('eau_electricite', 'Eau/Électricité'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_charge', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immeuble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='immeubles.immeuble')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='locaux.local')),
            ],
            options={
                'ordering': ['-date_charge'],
            },
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('immeuble__isnull', True), ('local__isnull', False)), models.Q(('immeuble__isnull', False), ('local__isnull', True)), _connector='OR'), name='chk_charge_local_xor_immeuble'),
        ),
    ]
