# Generated by Django 4.2.30 on 2026-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('immeuble__isnull', True), ('local__isnull', False)), models.Q(('immeuble__isnull', False), ('local__isnull', True)), _connector='OR'), name='chk_charge_local_xor_immeuble'),
        ),
    ]
