# Generated by Django 6.0.5 on 2026-05-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immeubles', '0001_initial'),
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_local', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('bureau', 'Bureau'), ('commerce', 'Commerce'), ('garage', 'Garage'), ('autre', 'Autre')], default='appartement', max_length=20)),
                ('adresse_province', models.CharField(blank=True, choices=[('Bujumbura', 'Bujumbura'), ('Gitega', 'Gitega'), ('Burunga', 'Burunga'), ('Butanyerera', 'Butanyerera'), ('Buhumuza', 'Buhumuza')], max_length=100)),
                ('adresse_commune', models.CharField(blank=True, max_length=100)),
                ('adresse_quartier', models.CharField(blank=True, max_length=100)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('annee_construction', models.IntegerField(blank=True, null=True)),
                ('meuble', models.BooleanField(default=False)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immeuble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locaux', to='immeubles.immeuble')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locaux', to='proprietaires.proprietaire')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
