# Generated by Django 4.2.30 on 2026-08-05 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locaux_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local',
            name='statut',
            field=models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('reserve', 'Réservé'), ('maintenance', 'En maintenance')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='local',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='local',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locaux_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
