# Generated by Django 4.2.30 on 2026-07-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0001_initial'),
        ('proprietaires', '0001_initial'),
        ('locaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_signature', models.DateField()),
                ('date_effet', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='actif', max_length=20)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
                ('periodicite_reversement', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel')], default='mensuel', max_length=20)),
                ('frais_entree', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_gestion_loyers', models.BooleanField(default=True)),
                ('service_quittances', models.BooleanField(default=True)),
                ('service_recherche_locataires', models.BooleanField(default=False)),
                ('service_gestion_travaux', models.BooleanField(default=False)),
                ('service_suivi_fiscal', models.BooleanField(default=False)),
                ('service_rapports', models.BooleanField(default=False)),
                ('service_loyers_impayes', models.BooleanField(default=False)),
                ('service_assurances', models.BooleanField(default=False)),
                ('service_judiciaire', models.BooleanField(default=False)),
                ('service_impots_locatifs', models.BooleanField(default=False)),
                ('service_clients', models.BooleanField(default=False)),
                ('service_touristique', models.BooleanField(default=False)),
                ('constat_lieu', models.BooleanField(default=False)),
                ('inventaire_immeuble', models.BooleanField(default=False)),
                ('clauses_particulieres', models.TextField(blank=True)),
                ('notes_internes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_societe', to='proprietaires.proprietaire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('resilie', 'Résilié'), ('expire', 'Expiré')], default='actif', max_length=20)),
                ('loyer_hors_charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provisions_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('bimensuel', 'Bi-mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20)),
                ('depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='locaux.local')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BordereauVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_virement', models.DateField()),
                ('reference_virement', models.CharField(blank=True, max_length=100, null=True)),
                ('banque', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier', models.CharField(max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('commentaire_admin', models.TextField(blank=True, null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contrat_societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux_virement', to='contrats.contratsociete')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux_virement', to='proprietaires.proprietaire')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(check=models.Q(('statut__in', ['actif', 'resilie', 'expire'])), name='chk_contrat_statut'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(check=models.Q(('periodicite__in', ['mensuel', 'bimensuel', 'trimestriel', 'semestriel', 'annuel'])), name='chk_contrat_periodicite'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(check=models.Q(('date_sortie__isnull', True), ('date_sortie__gt', models.F('date_entree')), _connector='OR'), name='chk_contrat_dates'),
        ),
    ]
