# Generated by Django 6.0.5 on 2026-05-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0001_initial'),
        ('locaux', '0001_initial'),
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('resilie', 'Résilié'), ('expire', 'Expiré')], default='actif', max_length=20)),
                ('loyer_hors_charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provisions_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('bimensuel', 'Bi-mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20)),
                ('depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='locaux.local')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_signature', models.DateField()),
                ('date_effet', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='actif', max_length=20)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
                ('periodicite_reversement', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel')], default='mensuel', max_length=20)),
                ('frais_entree', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_gestion_loyers', models.BooleanField(default=True)),
                ('service_quittances', models.BooleanField(default=True)),
                ('service_recherche_locataires', models.BooleanField(default=False)),
                ('service_gestion_travaux', models.BooleanField(default=False)),
                ('service_suivi_fiscal', models.BooleanField(default=False)),
                ('service_rapports', models.BooleanField(default=False)),
                ('service_loyers_impayes', models.BooleanField(default=False)),
                ('service_assurances', models.BooleanField(default=False)),
                ('service_judiciaire', models.BooleanField(default=False)),
                ('service_impots_locatifs', models.BooleanField(default=False)),
                ('service_clients', models.BooleanField(default=False)),
                ('service_touristique', models.BooleanField(default=False)),
                ('clauses_particulieres', models.TextField(blank=True)),
                ('notes_internes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_societe', to='proprietaires.proprietaire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
