# Generated by Django 4.2.30 on 2026-06-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratsociete',
            name='constat_lieu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratsociete',
            name='inventaire_immeuble',
            field=models.BooleanField(default=False),
        ),
    ]
