# Generated by Django 4.2.30 on 2026-08-05 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contrat',
            name='chk_contrat_statut',
        ),
        
        
        migrations.AddField(
            model_name='contrat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié'), ('renouvele', 'Renouvelé')], default='brouillon', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(check=models.Q(('statut__in', ['brouillon', 'actif', 'expire', 'resilie', 'renouvele'])), name='chk_contrat_statut'),
        ),
    ]
