# Generated by Django 4.2.30 on 2026-07-07 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietaires', '0002_proprietaire_mot_de_passe_temp'),
        ('contrats', '0002_contratsociete_constat_lieu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_virement', models.DateField()),
                ('reference_virement', models.CharField(blank=True, max_length=100, null=True)),
                ('banque', models.CharField(blank=True, max_length=100, null=True)),
                ('fichier', models.CharField(max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('commentaire_admin', models.TextField(blank=True, null=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contrat_societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux_virement', to='contrats.contratsociete')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux_virement', to='proprietaires.proprietaire')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
