# Generated by Django 4.2.30 on 2026-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_remove_contrat_chk_contrat_statut_contrat_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratsociete',
            name='frais_mise_location',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='contratsociete',
            name='frais_travaux_pct',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='contratsociete',
            name='loyer_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contratsociete',
            name='nombre_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratsociete',
            name='type_bien',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('bureau', 'Bureau'), ('commerce', 'Commerce'), ('garage', 'Garage'), ('autre', 'Autre')], max_length=30),
        ),
    ]
