# Generated by Django 4.2.30 on 2026-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_bordereauvirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(check=models.Q(('statut__in', ['actif', 'resilie', 'expire'])), name='chk_contrat_statut'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(check=models.Q(('periodicite__in', ['mensuel', 'bimensuel', 'trimestriel', 'semestriel', 'annuel'])), name='chk_contrat_periodicite'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.CheckConstraint(check=models.Q(('date_sortie__isnull', True), ('date_sortie__gt', models.F('date_entree')), _connector='OR'), name='chk_contrat_dates'),
        ),
        migrations.AddConstraint(
            model_name='contrat',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'actif')), fields=('local',), name='uniq_local_actif'),
        ),
    ]
