# Generated by Django 4.2.30 on 2026-09-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_contratsociete_frais_mise_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratsociete',
            old_name='loyer_mensuel',
            new_name='redevance_mensuelle',
        ),
    ]
