# Generated by Django 4.2.30 on 2026-07-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locaux', '0001_initial'),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('libelle', models.CharField(max_length=200)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('loyer_hors_charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('echeance', models.DateField()),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('partiel', 'Partiel'), ('paye', 'Payé'), ('retard', 'En retard')], default='attente', max_length=20)),
                ('quittance_envoyee', models.BooleanField(default=False)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='contrats.contrat')),
                ('local', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='locaux.local')),
                ('locataire', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-echeance'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='loyers.loyer')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Bordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', pyuploadcare.dj.models.ImageField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux', to='locataires.locataire')),
                ('loyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bordereaux', to='loyers.loyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
