# Generated by Django 4.2.30 on 2026-09-14 10:57

import apps.loyers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='banque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bordereau',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bordereau',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant payé par le locataire (hors frais de transaction)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bordereau',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bordereau',
            name='reference_client',
            field=models.CharField(default='', help_text='Référence de transaction saisie par le locataire (n° Mobile Money, virement, chèque, etc.)', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Loyers_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyer',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loyer',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Loyers_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='annule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='banque_operateur',
            field=models.CharField(blank=True, help_text="Nom de la banque ou de l'opérateur mobile money", max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaisses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='motif_annulation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(blank=True, help_text='Référence bancaire / mobile money de la transaction', max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bordereau',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=apps.loyers.models.bordereau_upload_path),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('partiel', 'Partiellement payé'), ('paye', 'Payé'), ('retard', 'En retard'), ('annule', 'Annulé')], default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
