# Generated by Django 4.2.30 on 2026-06-12 12:01

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereau',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
