# Generated by Django 4.2.30 on 2026-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0002_alter_bordereau_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyer',
            name='quittance_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
