# Generated by Django 4.2.30 on 2026-07-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locaux', '0001_initial'),
        ('contrats', '0004_contrat_deleted_at_contrat_chk_contrat_statut_and_more'),
        ('locataires', '0005_locataire_uniq_locataire_email_and_more'),
        ('loyers', '0003_loyer_quittance_envoyee'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='contrats.contrat'),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='local',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='locaux.local'),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='locataire',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='loyers', to='locataires.locataire'),
        ),
    ]
