# Generated by Django 4.2.30 on 2026-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0003_paiement_annule_paiement_annule_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
