# Generated by Django 4.2.30 on 2026-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0005_backfill_numeros_bordereaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereau',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
