# Generated by Django 4.2.30 on 2026-08-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0006_alter_bordereau_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereau',
            name='reference_client',
            field=models.CharField(blank=True, help_text='Référence de transaction saisie par le locataire (n° Mobile Money, virement, chèque, etc.)', max_length=100),
        ),
    ]
