# Generated by Django 6.0.5 on 2026-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse_province', models.CharField(blank=True, choices=[('Bujumbura', 'Bujumbura'), ('Gitega', 'Gitega'), ('Burunga', 'Burunga'), ('Butanyerera', 'Butanyerera'), ('Buhumuza', 'Buhumuza')], max_length=100)),
                ('adresse_commune', models.CharField(blank=True, max_length=100)),
                ('adresse_quartier', models.CharField(blank=True, max_length=100)),
                ('annee_construction', models.IntegerField(blank=True, null=True)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
