# Generated by Django 4.2.30 on 2026-07-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse_province', models.CharField(blank=True, choices=[('Buhumuza', 'Buhumuza'), ('Bujumbura', 'Bujumbura'), ('Burunga', 'Burunga'), ('Butanyerera', 'Butanyerera'), ('Gitega', 'Gitega')], max_length=100)),
                ('adresse_commune', models.CharField(blank=True, max_length=100)),
                ('adresse_quartier', models.CharField(blank=True, max_length=100)),
                ('annee_construction', models.IntegerField(blank=True, null=True)),
                ('informations_complementaires', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immeubles', to='proprietaires.proprietaire')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
