# Generated by Django 4.2.30 on 2026-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeubles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immeuble',
            options={'ordering': ['nom'], 'verbose_name': 'Immeuble', 'verbose_name_plural': 'Immeubles'},
        ),
        migrations.AddField(
            model_name='immeuble',
            name='adresse_complement',
            field=models.CharField(blank=True, help_text='Rue, numéro, avenue, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='continent',
            field=models.CharField(blank=True, choices=[('Afrique', 'Afrique'), ('Europe', 'Europe'), ('Amériques', 'Amériques'), ('Asie', 'Asie'), ('Océanie', 'Océanie')], help_text="Continent de l'immeuble", max_length=50),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='pays',
            field=models.CharField(blank=True, choices=[('Burundi', 'Burundi'), ('Rwanda', 'Rwanda'), ('RDC', 'RDC'), ('Tanzanie', 'Tanzanie'), ('Kenya', 'Kenya'), ('Ouganda', 'Ouganda'), ('Éthiopie', 'Éthiopie'), ('Somalie', 'Somalie'), ('Soudan du Sud', 'Soudan du Sud'), ('Cameroun', 'Cameroun'), ('Gabon', 'Gabon'), ('Congo-Brazzaville', 'Congo-Brazzaville'), ('Tchad', 'Tchad'), ('RCA', 'RCA'), ('Sénégal', 'Sénégal'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Mali', 'Mali'), ('Burkina Faso', 'Burkina Faso'), ('Niger', 'Niger'), ('Guinée', 'Guinée'), ('Bénin', 'Bénin'), ('Togo', 'Togo'), ('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Sierra Leone', 'Sierra Leone'), ('Liberia', 'Liberia'), ('Mauritanie', 'Mauritanie'), ('Égypte', 'Égypte'), ('Maroc', 'Maroc'), ('Algérie', 'Algérie'), ('Tunisie', 'Tunisie'), ('Libye', 'Libye'), ('Afrique du Sud', 'Afrique du Sud'), ('Zimbabwe', 'Zimbabwe'), ('Zambie', 'Zambie'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Angola', 'Angola'), ('Namibie', 'Namibie'), ('Botswana', 'Botswana'), ('Madagascar', 'Madagascar'), ('Maurice', 'Maurice'), ('France', 'France'), ('Belgique', 'Belgique'), ('Suisse', 'Suisse'), ('Allemagne', 'Allemagne'), ('Royaume-Uni', 'Royaume-Uni'), ('Espagne', 'Espagne'), ('Italie', 'Italie'), ('Portugal', 'Portugal'), ('Pays-Bas', 'Pays-Bas'), ('Luxembourg', 'Luxembourg'), ('Autriche', 'Autriche'), ('Suède', 'Suède'), ('Norvège', 'Norvège'), ('Danemark', 'Danemark'), ('Finlande', 'Finlande'), ('Irlande', 'Irlande'), ('Pologne', 'Pologne'), ('République tchèque', 'République tchèque'), ('Grèce', 'Grèce'), ('Turquie', 'Turquie'), ('Russie', 'Russie'), ('Canada', 'Canada'), ('États-Unis', 'États-Unis'), ('Mexique', 'Mexique'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('Costa Rica', 'Costa Rica'), ('Panama', 'Panama'), ('Cuba', 'Cuba'), ('Haïti', 'Haïti'), ('République dominicaine', 'République dominicaine'), ('Jamaïque', 'Jamaïque'), ('Brésil', 'Brésil'), ('Argentine', 'Argentine'), ('Chili', 'Chili'), ('Colombie', 'Colombie'), ('Pérou', 'Pérou'), ('Venezuela', 'Venezuela'), ('Équateur', 'Équateur'), ('Bolivie', 'Bolivie'), ('Uruguay', 'Uruguay'), ('Paraguay', 'Paraguay'), ('Émirats arabes unis', 'Émirats arabes unis'), ('Arabie saoudite', 'Arabie saoudite'), ('Qatar', 'Qatar'), ('Koweït', 'Koweït'), ('Bahreïn', 'Bahreïn'), ('Oman', 'Oman'), ('Jordanie', 'Jordanie'), ('Liban', 'Liban'), ('Israël', 'Israël'), ('Iran', 'Iran'), ('Irak', 'Irak'), ('Inde', 'Inde'), ('Pakistan', 'Pakistan'), ('Bangladesh', 'Bangladesh'), ('Sri Lanka', 'Sri Lanka'), ('Népal', 'Népal'), ('Thaïlande', 'Thaïlande'), ('Vietnam', 'Vietnam'), ('Indonésie', 'Indonésie'), ('Malaisie', 'Malaisie'), ('Singapour', 'Singapour'), ('Philippines', 'Philippines'), ('Cambodge', 'Cambodge'), ('Myanmar', 'Myanmar'), ('Chine', 'Chine'), ('Japon', 'Japon'), ('Corée du Sud', 'Corée du Sud'), ('Taïwan', 'Taïwan'), ('Hong Kong', 'Hong Kong'), ('Macao', 'Macao'), ('Mongolie', 'Mongolie'), ('Australie', 'Australie'), ('Nouvelle-Zélande', 'Nouvelle-Zélande'), ('Fidji', 'Fidji'), ('Papouasie-Nouvelle-Guinée', 'Papouasie-Nouvelle-Guinée')], help_text="Pays de l'immeuble", max_length=100),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='adresse_commune',
            field=models.CharField(blank=True, help_text='Commune / ville', max_length=100),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='adresse_province',
            field=models.CharField(blank=True, help_text='Province / région / état', max_length=100),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='adresse_quartier',
            field=models.CharField(blank=True, help_text='Quartier / zone', max_length=100),
        ),
    ]
