# Generated by Django 4.2.30 on 2026-06-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprietaires', '0002_proprietaire_mot_de_passe_temp'),
        ('immeubles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immeuble',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immeubles', to='proprietaires.proprietaire'),
        ),
    ]
