# Generated by Django 4.2.30 on 2026-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeubles', '0002_immeuble_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immeuble',
            name='adresse_province',
            field=models.CharField(blank=True, choices=[('Buhumuza', 'Buhumuza'), ('Bujumbura', 'Bujumbura'), ('Burunga', 'Burunga'), ('Butanyerera', 'Butanyerera'), ('Gitega', 'Gitega')], max_length=100),
        ),
    ]
