# Generated by Django 6.0.5 on 2026-05-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notif', models.CharField(choices=[('paiement', 'Paiement'), ('bordereau', 'Bordereau'), ('rappel', 'Rappel'), ('message', 'Message'), ('avertissement', 'Avertissement')], default='rappel', max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire_locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='locataires.locataire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
